export interface ExerciseMeta {
  id: string;
  n: number;
  path: string;
  title: string;
  topic: string;
  summary: string;
  done?: boolean;
}

export const EXERCISES: ExerciseMeta[] = [
  {
    id: 'ex01',
    n: 1,
    path: 'ex01-signals',
    title: 'Signals: signal / computed / effect',
    topic: 'Reattività',
    summary: 'Stato locale reattivo, valori derivati e side-effect senza RxJS.',
    done: true,
  },
  {
    id: 'ex02',
    n: 2,
    path: 'ex02-control-flow',
    title: 'Nuovo control flow: @if / @for / @switch',
    topic: 'Template',
    summary: 'Sintassi built-in, @empty, blocco @else, track e $index.',
    done: true,
  },
  {
    id: 'ex03',
    n: 3,
    path: 'ex03-signal-io',
    title: 'Signal inputs & outputs',
    topic: 'Componenti',
    summary: 'input(), input.required(), alias, transform, output().',
    done: true,
  },
  {
    id: 'ex04',
    n: 4,
    path: 'ex04-model',
    title: 'model(): two-way binding con i signal',
    topic: 'Componenti',
    summary: 'Creare un componente con binding [(value)] usando model().',
    done: true,
  },
  {
    id: 'ex05',
    n: 5,
    path: 'ex05-queries',
    title: 'Query come signal: viewChild / viewChildren',
    topic: 'Componenti',
    summary: 'viewChild.required, contentChild, reagire alle query con effect.',
    done: true,
  },
  {
    id: 'ex06',
    n: 6,
    path: 'ex06-linked-signal',
    title: 'linkedSignal: stato derivato ma scrivibile',
    topic: 'Reattività',
    summary: 'Selezione che si resetta quando cambia la lista sorgente.',
    done: true,
  },
  {
    id: 'ex07',
    n: 7,
    path: 'ex07-resource',
    title: 'resource(): async con loading / error / reload',
    topic: 'Dati async',
    summary: 'Caricamento asincrono legato a un parametro reattivo.',
    done: true,
  },
  {
    id: 'ex08',
    n: 8,
    path: 'ex08-http-resource',
    title: 'httpResource(): REST dichiarativo',
    topic: 'Dati async',
    summary: 'Fetch HTTP reattivo con parametri e stato di errore.',
    done: true,
  },
  {
    id: 'ex09',
    n: 9,
    path: 'ex09-defer',
    title: 'Deferrable views: @defer',
    topic: 'Performance',
    summary: 'Lazy loading di parte di template con @placeholder/@loading/@error.',
    done: true,
  },
  {
    id: 'ex10',
    n: 10,
    path: 'ex10-guards-interceptors',
    title: 'Functional guard + interceptor + input binding di rotta',
    topic: 'Router / HTTP',
    summary: 'CanActivateFn, HttpInterceptorFn, withComponentInputBinding().',
    done: true,
  },
  {
    id: 'ex11',
    n: 11,
    path: 'ex11-content-projection',
    title: 'Content projection avanzata: ng-content, select, ngProjectAs',
    topic: 'Componenti',
    summary: 'Slot multipli con ng-content select e ngProjectAs.',
    done: true,
  },
  {
    id: 'ex12',
    n: 12,
    path: 'ex12-dependency-injection',
    title: 'Dependency Injection: inject(), InjectionToken, provider gerarchici',
    topic: 'Architettura',
    summary: 'inject(), token custom, provider a livello di componente, multi provider.',
    done: true,
  },
  {
    id: 'ex13',
    n: 13,
    path: 'ex13-custom-directives',
    title: 'Direttive custom + Directive Composition API',
    topic: 'Componenti',
    summary: 'host binding moderno e hostDirectives per comporre comportamento.',
    done: true,
  },
  {
    id: 'ex14',
    n: 14,
    path: 'ex14-reactive-forms',
    title: 'Reactive Forms tipizzati: validatori custom e incrociati',
    topic: 'Form',
    summary: 'Typed FormGroup/FormControl, validatore custom e cross-field.',
    done: true,
  },
  {
    id: 'ex15',
    n: 15,
    path: 'ex15-rxjs-signals-interop',
    title: 'RxJS ↔ Signals: toObservable, toSignal',
    topic: 'Dati async',
    summary: 'Search box con debounce/switchMap e interop signal-observable.',
    done: true,
  },
  {
    id: 'ex16',
    n: 16,
    path: 'ex16-native-animations',
    title: 'Animazioni native: animate.enter / animate.leave',
    topic: 'Template',
    summary: 'Animazioni CSS-driven per elementi che entrano/escono dal DOM.',
    done: true,
  },
  {
    id: 'ex17',
    n: 17,
    path: 'ex17-testing',
    title: 'Testare un componente con signal: TestBed',
    topic: 'Testing',
    summary: 'TestBed, ComponentFixture, asserzioni su stato e DOM.',
    done: true,
  },
  {
    id: 'ex18',
    n: 18,
    path: 'ex18-router-resolvers',
    title: 'Router avanzato: resolver funzionali e route data',
    topic: 'Router / HTTP',
    summary: 'ResolveFn, route data legata a input via withComponentInputBinding().',
    done: true,
  },
  {
    id: 'ex19',
    n: 19,
    path: 'ex19-afterrender-host-bindings',
    title: 'DOM diretto dopo il render: afterRenderEffect',
    topic: 'Performance',
    summary: 'Disegno su canvas reattivo dopo il render, host binding sul componente.',
  },
  {
    id: 'ex20',
    n: 20,
    path: 'ex20-signal-store',
    title: 'State management: uno store con signal',
    topic: 'Architettura',
    summary: 'Servizio singleton con signal privati, computed selector, update immutabili.',
  },
  {
    id: 'ex21',
    n: 21,
    path: 'ex21-custom-pipes',
    title: 'Pipe custom: pure vs impure',
    topic: 'Template',
    summary: 'Pipe pura per il troncamento di stringhe, pipe impura per un orologio live.',
  },
  {
    id: 'ex22',
    n: 22,
    path: 'ex22-structural-directives',
    title: 'Direttiva strutturale custom: TemplateRef + ViewContainerRef',
    topic: 'Componenti',
    summary: '*appUnless e *appRepeat scritte da zero, come funziona *ngIf sotto il cofano.',
  },
  {
    id: 'ex23',
    n: 23,
    path: 'ex23-environment-providers',
    title: 'Environment providers: provideXxx() e provideAppInitializer',
    topic: 'Architettura',
    summary: 'Funzione provideAnalytics() in stile provideRouter/provideHttpClient.',
  },
  {
    id: 'ex24',
    n: 24,
    path: 'ex24-advanced-signals',
    title: 'Signal avanzati: untracked(), effect cleanup, equal custom',
    topic: 'Reattività',
    summary: 'Debounce via cleanup, lettura non tracciata, comparatore equal personalizzato.',
  },
  {
    id: 'ex25',
    n: 25,
    path: 'ex25-error-handling',
    title: 'Error handling: ErrorHandler globale + catchError/retry',
    topic: 'Architettura',
    summary: 'Rete di sicurezza globale vs gestione puntuale degli errori HTTP.',
  },
  {
    id: 'ex26',
    n: 26,
    path: 'ex26-ng-optimized-image',
    title: 'NgOptimizedImage: immagini performanti senza sforzo',
    topic: 'Performance',
    summary: 'ngSrc, priority, dimensioni obbligatorie per evitare layout shift.',
  },
  {
    id: 'ex27',
    n: 27,
    path: 'ex27-icu-i18n',
    title: 'Espressioni ICU: plural e select nel template',
    topic: 'Template',
    summary: 'Testo condizionale su un valore, compilato client-side senza estrazione i18n.',
  },
  {
    id: 'ex28',
    n: 28,
    path: 'ex28-preloading-strategy',
    title: 'Router: PreloadingStrategy custom',
    topic: 'Router / HTTP',
    summary: 'Precaricamento selettivo dei chunk lazy in base a route data.',
  },
  {
    id: 'ex29',
    n: 29,
    path: 'ex29-title-strategy',
    title: 'Router: TitleStrategy custom, titoli di pagina dinamici',
    topic: 'Router / HTTP',
    summary: 'Suffisso automatico sul <title> del documento ad ogni navigazione.',
  },
  {
    id: 'ex30',
    n: 30,
    path: 'ex30-dynamic-components',
    title: 'Creazione dinamica di componenti: ViewContainerRef.createComponent()',
    topic: 'Componenti',
    summary: 'Un mini servizio di toast creato imperativamente, non dal template.',
  },
];
